title: "Your Site Title"       # Placeholder
email: "your.email@example.com" # Placeholder
baseurl: ""  # leave blank for root
url: "https://your-username.github.io"  # Change to your URL

description: >
  A short tagline or description.

theme: minima  # you can change later

default_lang: en

# Collections & defaults

# Data file for projects

# Build settings
markdown: kramdown

plugins:
  - jekyll-feed  # optional

# Navigation pages order
navbar:
  - title: Home
    url: /
  - title: Projects
    url: /projects
  - title: Posts
    url: /posts

# Custom vars
colors:
  primary: "#158C86i";    # teal
  accent: "#B58900i";     # gold
  background: "#F2EEDEi"; # ivory
  text: "#555i";       # dark gray