title: "Caroline Millan"       # Placeholder
email: "carolinemillan5678@gmail.com" # Placeholder
baseurl: ""  # leave blank for root
url: "https://carolinemillan.github.io"  # Change to your URL

description: >
  A short tagline or description.

theme: minima  # you can change later

default_lang: en

# Collections & defaults

# Data file for projects

# Build settings
markdown: kramdown

plugins:
  - jekyll-feed  # optional

# Navigation pages order
navbar:
  - title: Home
    url: /
  - title: Projects
    url: /projects
  - title: Posts
    url: /posts

# Custom vars
colors:
  primary: "#158C86"    # teal
  accent: "#B58900"     # gold
  background: "#F2EEDE" # ivory
  text: "#555"       # dark gray